version: "3"

services:

  svn:
    image: sangah/apache-svn
    volumes: 
    - ${SVN_ROOT_FOLDER}:/mnt/svn/
    - ${SVN_HTPASSWD_PATH}:/etc/apache2/.htaccess:ro
    ports:
    - "${HTTP_PORT}:80"
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"