version: "3"

services:

  sync:
    image: sangah/apache-svn
    volumes: 
    - ${SVN_ROOT_FOLDER}:/mnt/svn/
    - ${SVN_HTPASSWD_PATH}:/etc/apache2/.htaccess:ro
    - $PWD/tmp:/mnt/tmp/
    command: svnsync sync --steal-lock file:///mnt/svn/repos
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"