version: "3"

services:

  svn:
    build: svn
    volumes: 
    - ${SVN_ROOT_FOLDER}:/mnt/svn/
    - ${SVN_HTPASSWD_PATH}:/etc/apache2/.htaccess:ro
    - ${SVN_ACCESS_FILE}:/etc/apache2/.svnaccess:ro
    ports:
    - "${HTTP_PORT}:80"